"""
LabelGuard AI — Compliance Report Generator
Builds structured JSON reports and plain-text export summaries.
"""

from datetime import datetime


def generate_report(
    raw_text: str,
    extracted_fields: dict,
    rule_results: dict,
    filename: str = "unknown",
) -> dict:
    """
    Generate a complete compliance report combining OCR output + rule validation.
    """
    now = datetime.now()

    # Determine overall status
    pct = rule_results["compliance_percentage"]
    if pct >= 90:
        overall_status = "Compliant"
    elif pct >= 60:
        overall_status = "Review needed"
    else:
        overall_status = "Non-compliant"

    report = {
        "report_id": f"REP-{now.strftime('%Y')}-{now.strftime('%m%d%H%M')}",
        "generated_at": now.isoformat(),
        "source_file": filename,
        "overall_status": overall_status,
        "compliance_percentage": pct,
        "total_rules": rule_results["total_rules"],
        "rules_passed": rule_results["passed"],
        "rules_failed": rule_results["failed"],
        "extracted_fields": _serialize_fields(extracted_fields),
        "rule_results": rule_results["results"],
        "raw_ocr_text": raw_text[:2000],
    }

    return report


def export_text(report: dict) -> str:
    """Generate a plain-text version of the compliance report."""
    lines = [
        "=" * 60,
        "  LABELGUARD AI — COMPLIANCE REPORT",
        "=" * 60,
        "",
        f"  Report ID     : {report['report_id']}",
        f"  Generated     : {report['generated_at']}",
        f"  Source File    : {report['source_file']}",
        f"  Overall Status : {report['overall_status']}",
        f"  Compliance     : {report['compliance_percentage']}%",
        f"  Rules Passed   : {report['rules_passed']} / {report['total_rules']}",
        f"  Rules Failed   : {report['rules_failed']} / {report['total_rules']}",
        "",
        "-" * 60,
        "  EXTRACTED FIELDS",
        "-" * 60,
    ]

    for key, value in report["extracted_fields"].items():
        label = key.replace("_", " ").title()
        lines.append(f"  {label:30s} : {value}")

    lines.extend([
        "",
        "-" * 60,
        "  RULE-BY-RULE RESULTS",
        "-" * 60,
    ])

    for r in report["rule_results"]:
        icon = "✓ PASS" if r["status"] == "pass" else "✗ FAIL"
        lines.append(f"")
        lines.append(f"  [{r['rule_id']}] {r['rule_name']}")
        lines.append(f"       Section  : {r['section']}")
        lines.append(f"       Status   : {icon}")
        lines.append(f"       Value    : {r['extracted_value']}")
        lines.append(f"       Detail   : {r['detail']}")

    lines.extend([
        "",
        "=" * 60,
        "  Legal Metrology (Packaged Commodities) Rules, 2011",
        "  Report generated by LabelGuard AI",
        "=" * 60,
    ])

    return "\n".join(lines)


def _serialize_fields(fields: dict) -> dict:
    """Convert extracted fields to JSON-safe format."""
    serialized = {}
    for key, value in fields.items():
        if value is None:
            serialized[key] = "Not detected"
        elif isinstance(value, dict):
            if not value:
                serialized[key] = "Not detected"
            else:
                parts = [f"{k}: {v}" for k, v in value.items()]
                serialized[key] = " | ".join(parts)
        else:
            serialized[key] = str(value)
    return serialized
